### ISSUE TITLE
moi_list.init should have a parameter to specify the destination in the DOM

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/mustached-octo-ironman#17]
As part of `moi_list`'s initialization, the object is appended to the body of the current document. I think it would be better to allow an extra argument to be passed, this argument would indicate the id of the element where the list should be appended to, for example:

```javascript
this.init = function (group_id, destination) {
// initialization code
}

// usage
moi_list.init('xxxxxxxxxxx', 'updates-div');
```

**Comment by adamrp** [comment]
:+1:

**Comment by wasade** [comment]
:+1:

**Comment by wasade** [comment]
@ElDeveloper, do you think this would be relatively straight forward to do? My impression is that all that is necessary is to accept the div [here](https://github.com/biocore/mustached-octo-ironman/blob/master/moi/support_files/moi_list.js#L116) and use that instead of the forces default of `div` [here](https://github.com/biocore/mustached-octo-ironman/blob/master/moi/support_files/moi_list.js#L118). If so, will push this in tonight

**Comment by ElDeveloper** [comment]
@wasade, yes I think that's exactly what's needed. I'm not sure what the 'javascripthonic' way to do it but either a div or a div-id would be fine (perhaps div-id).

**Comment by adamrp** [comment]
Maybe both would be convenient? Type check, and if the user passes a div,
use that div, and if they pass a div id, create the new div (possibly with
a unique id that is returned by the function?)

**Comment by adamrp** [comment]
Er, sorry, that was a combination of thoughts... never mind about the
unique id
