### ISSUE TITLE
Improve installation process

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/mustached-octo-ironman#20]
In order for someone to install moi in their project, the JS source needs to be manually copied and kept (manually) up to date in the other project. It would be great if this process could be automated.

**Comment by wasade** [comment]
This isn't automated necessarily, but there are now support methods (e.g., `moi.moi_js` which provide the necessary filepaths. I believe this is sufficient as an upstream package can use those methods to copy the `.js` to where ever they need to go. Closing because of this, please open if closed in error.
